<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Product_total_product</name>
   <tag></tag>
   <elementGuidId>04c74763-2aef-47df-8149-164e06cf8ce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;total_product&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='total_product']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e00869ed-61f8-42e8-8352-61f786327f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ade7dcc9-6b06-4b9d-aed0-7547f56b13b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>total_product</value>
      <webElementGuid>23fe3aa4-d9b5-4ed2-9312-8c64895e13f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>9f492604-266b-4db5-9903-0e8ce3c96d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-2 px-3 border-2 border-gray-400 rounded-lg focus:outline-none</value>
      <webElementGuid>5296c204-fc5f-4d4b-9237-bf71d2563eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-[#F2F2F2]&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;w-full ml-[255px]&quot;]/div[@class=&quot;px-6 w-full flex gap-6&quot;]/div[@class=&quot;w-3/5&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full p-6 bg-white rounded-lg mt-5&quot;]/div[@class=&quot;flex justify-between items-center gap-6 mb-4&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;w-full py-2 px-3 border-2 border-gray-400 rounded-lg focus:outline-none&quot;]</value>
      <webElementGuid>aa3fe555-b567-4d27-b7c7-1acd1b9af53e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='total_product']</value>
      <webElementGuid>d5adb0bb-fe01-47c1-85d8-72d991f6a3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>c946644c-7a7a-4274-b5b4-f2fa602ea5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>a1434673-466d-4873-8552-8070942113c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'total_product' and @placeholder = '5']</value>
      <webElementGuid>dca28f18-c269-401c-bd59-4946f6b982fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
