<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Patung kuda yang dibuat deng</name>
   <tag></tag>
   <elementGuidId>dda191f4-be6c-4194-8f2f-5261168897ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deskrisi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='deskrisi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7332671c-c066-4a07-bb35-12cfb3af913e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>5bdaac6d-475d-4fdf-9999-0288c04b51d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deskrisi</value>
      <webElementGuid>d61b92dd-08fa-483f-b6fd-dca4766b826f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>0c8a6984-1ef3-411c-965e-c960b579f810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-2 px-3 border-2 border-gray-400 rounded-lg focus:outline-none overflow-auto</value>
      <webElementGuid>e7e3906a-b9c6-48e2-8cc5-b032a9a81ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patung kuda yang dibuat deng</value>
      <webElementGuid>3c2bdc77-23a7-4bd8-acc7-bfb2afd7225d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deskrisi&quot;)</value>
      <webElementGuid>e0e101fe-7320-459c-a118-d0fcb57e6997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='deskrisi']</value>
      <webElementGuid>2934808d-28a5-4bc3-87dc-dd5b12b187e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div/div/div/div[4]/textarea</value>
      <webElementGuid>10d6a353-f440-477f-82a9-72addf180906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Product'])[1]/following::textarea[1]</value>
      <webElementGuid>5486a775-8587-4b60-9f57-82daa2f09fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Product'])[1]/following::textarea[1]</value>
      <webElementGuid>0577ad28-facb-40fc-8040-2a2cd18b53a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media'])[1]/preceding::textarea[1]</value>
      <webElementGuid>96009431-e1f7-43e4-b5d4-4fda7ccb90e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/preceding::textarea[1]</value>
      <webElementGuid>6daf853e-e356-419d-aa1e-e760f563ce0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Patung kuda yang dibuat deng']/parent::*</value>
      <webElementGuid>d6f54897-db5f-4110-bb03-97facdfb2373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1e4c041f-48b2-4975-82d8-c0462afcff0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @id = 'deskrisi' and (text() = 'Patung kuda yang dibuat deng' or . = 'Patung kuda yang dibuat deng')]</value>
      <webElementGuid>f96d200b-820d-4da2-9aa9-9c0a4a0f35f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
