<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Patung kuda yang dibuat dengan tek_a6d3b2</name>
   <tag></tag>
   <elementGuidId>90fb16dc-cdec-41e7-8013-38a77ebe0735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deskrisi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='deskrisi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>73841d7e-f8e8-4db5-9fc6-d37b16d4f14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>1f74a4f0-4eb8-4f3a-aa9d-87dbf4d8311c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deskrisi</value>
      <webElementGuid>5b7f3117-3b1e-432a-9c17-c091668ec33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>cf525bb2-90ab-4238-952a-11a0f6515824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-2 px-3 border-2 border-gray-400 rounded-lg focus:outline-none overflow-auto</value>
      <webElementGuid>5f47e19d-e5f2-4948-9557-719b339cf7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patung kuda yang dibuat dengan teknologi 3DPRin</value>
      <webElementGuid>54dd49a8-2464-4684-ae3a-8e5ee3f2da8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deskrisi&quot;)</value>
      <webElementGuid>3f42227e-ef16-4515-b993-7b09ac5d589e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='deskrisi']</value>
      <webElementGuid>fb126a4d-77be-482a-afab-44d2479883c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div/div/div/div[4]/textarea</value>
      <webElementGuid>de1b227e-542a-4061-b2cd-600406c4fbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Product'])[1]/following::textarea[1]</value>
      <webElementGuid>80572b0b-5959-40ae-bff7-1ae87244c91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Product'])[1]/following::textarea[1]</value>
      <webElementGuid>be93557d-4f25-45af-a132-6fec963a81ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d7dd287f-d04b-48bd-a838-b351e9a39275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8235e1c5-3e8c-4113-9543-4fe02a107242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Patung kuda yang dibuat dengan teknologi 3DPRin']/parent::*</value>
      <webElementGuid>d4da80bc-7b26-4b10-b7e4-40403f2f248a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7271e1e8-246f-4bca-adfa-0686f3d8b2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @id = 'deskrisi' and (text() = 'Patung kuda yang dibuat dengan teknologi 3DPRin' or . = 'Patung kuda yang dibuat dengan teknologi 3DPRin')]</value>
      <webElementGuid>397c4a5d-02a5-4c09-afc3-9b2f1db86f6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
