<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Patung kuda yang dibuat dengan tek_03fa73_1_2</name>
   <tag></tag>
   <elementGuidId>ec959d20-a2ce-4733-b0db-7c03ac63ef60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deskrisi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='deskrisi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2da349c2-bc54-4016-8e90-4eb19d7d1a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>61a065ad-8651-430c-b279-9d456cddced2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deskrisi</value>
      <webElementGuid>977faefa-65ec-4204-b19f-86a856b9a8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>a4278ffd-5f2e-4098-9bc5-6077806438fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-2 px-3 border-2 border-gray-400 rounded-lg focus:outline-none overflow-auto</value>
      <webElementGuid>35ec3762-d979-4c5f-91a1-9c582c317f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patung kuda yang dibuat dengan teknologi 3D Printing terkini. </value>
      <webElementGuid>361b9743-ae90-4dd4-b6d8-e31a99c1c031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deskrisi&quot;)</value>
      <webElementGuid>fc87825a-4903-402e-85c7-bd235e1ccf5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='deskrisi']</value>
      <webElementGuid>3b2e10fa-de11-479e-a758-827f1e1a50d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div/div/div/div[4]/textarea</value>
      <webElementGuid>bf7d662d-b30b-492e-b3ac-9587cd7d0b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Product'])[1]/following::textarea[1]</value>
      <webElementGuid>4d899917-ef8d-455b-81c3-0d8f5515bdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Product'])[1]/following::textarea[1]</value>
      <webElementGuid>0f48b892-0d91-499d-9a45-1fac004a1dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d6da66ef-37be-4dc4-ab8a-befdafe6fb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/preceding::textarea[1]</value>
      <webElementGuid>cfdb3cf8-aaaa-46e6-adb8-1ca60f0fe3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Patung kuda yang dibuat dengan teknologi 3D Printing terkini.']/parent::*</value>
      <webElementGuid>96939023-7ee9-4fa6-9948-1d93bd59d3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>00b50d0c-0f7a-4bcb-8497-837464335a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @id = 'deskrisi' and (text() = 'Patung kuda yang dibuat dengan teknologi 3D Printing terkini. ' or . = 'Patung kuda yang dibuat dengan teknologi 3D Printing terkini. ')]</value>
      <webElementGuid>587fbbe7-c927-4c99-95dc-424e97e5bffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
