<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Patung kuda yang dibuat</name>
   <tag></tag>
   <elementGuidId>5499fe80-27a7-439d-8124-d7e1e78ea433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deskrisi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='deskrisi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>370593d0-4280-4b02-b47c-aab19330386b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>4e14ac22-0517-4256-8c15-2707d54501bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deskrisi</value>
      <webElementGuid>125fe998-2c7f-4454-b1bb-81e7002e98f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>dbbe3d84-badb-46b6-b254-7a2d00fc48bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-2 px-3 border-2 border-gray-400 rounded-lg focus:outline-none overflow-auto</value>
      <webElementGuid>a2333553-ac03-4d59-a078-62ebe525e83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patung kuda yang dibuat</value>
      <webElementGuid>aed1452f-fd3f-407a-90d0-ac4e3d6ec71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deskrisi&quot;)</value>
      <webElementGuid>e3fa65cb-6a1f-46e9-8904-db19c162e937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='deskrisi']</value>
      <webElementGuid>e080c0ff-6aef-4c08-84ab-b8a081d3af58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div/div/div/div[4]/textarea</value>
      <webElementGuid>5634b156-fb2c-4e37-a45d-6ff882f52fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Product'])[1]/following::textarea[1]</value>
      <webElementGuid>35639718-ca84-420f-b07b-1df786ad1326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Product'])[1]/following::textarea[1]</value>
      <webElementGuid>8eaa7b68-25e0-4503-8e05-b93a265d8953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media'])[1]/preceding::textarea[1]</value>
      <webElementGuid>512bc07b-e7ab-47fb-af69-e8e278583999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/preceding::textarea[1]</value>
      <webElementGuid>58183493-0fe5-4814-b1f9-78fea9c89db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Patung kuda yang dibuat']/parent::*</value>
      <webElementGuid>46d1da78-45c5-41d6-9830-00c5356dab2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c96f804a-e2db-4206-911c-a4b2263e6251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @id = 'deskrisi' and (text() = 'Patung kuda yang dibuat' or . = 'Patung kuda yang dibuat')]</value>
      <webElementGuid>4e773e3c-f99e-4e2d-acd8-640b3e3d7678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
