<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Patung kuda yang dibuat dengan tek_5d7886</name>
   <tag></tag>
   <elementGuidId>b83badc8-d691-4f4e-996b-de84010c79ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deskrisi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='deskrisi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9280831d-0317-4033-ab25-183a9cc4bbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>9263cc6e-0052-4baf-9a57-28e8a65040c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deskrisi</value>
      <webElementGuid>b2c88f34-0fbe-445f-8a68-1e898f04dafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>a33dbcb3-43b1-4b46-a814-ac89b235b9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-2 px-3 border-2 border-gray-400 rounded-lg focus:outline-none overflow-auto</value>
      <webElementGuid>66ed2d72-6594-4cd2-9a5d-acad2f956189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patung kuda yang dibuat dengan teknologi 3D Printing ter</value>
      <webElementGuid>d497e74f-f6f9-4376-9756-da42ebaa3525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deskrisi&quot;)</value>
      <webElementGuid>5c2057df-6e13-4ffa-b0e9-07e0618e5466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='deskrisi']</value>
      <webElementGuid>5c298587-680b-4a7e-a3e1-8ba77f049c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div/div/div/div[4]/textarea</value>
      <webElementGuid>6ef304f1-2b0d-4eee-98ad-f134636af47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Product'])[1]/following::textarea[1]</value>
      <webElementGuid>1eec9248-061d-4e67-8933-96d5f15905fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Product'])[1]/following::textarea[1]</value>
      <webElementGuid>3077d29e-b570-42e6-aec7-ddea16ce6a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d90ddd20-8a6f-4777-a741-be456d1dfde1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7469a201-6b8d-4340-9a89-55c693b49b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Patung kuda yang dibuat dengan teknologi 3D Printing ter']/parent::*</value>
      <webElementGuid>d9e08c6d-14e2-4780-b271-2034839d6456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>86a3ab89-bd2e-4640-aba8-93909c7d1c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @id = 'deskrisi' and (text() = 'Patung kuda yang dibuat dengan teknologi 3D Printing ter' or . = 'Patung kuda yang dibuat dengan teknologi 3D Printing ter')]</value>
      <webElementGuid>52447edf-fb22-4974-acc9-6e40561a09df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
