<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Batang_kodeBatang</name>
   <tag></tag>
   <elementGuidId>29deee14-b247-4582-ad07-fe11c2e4f249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kodeBatang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kodeBatang&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2087c9f3-c52b-40cd-a9d8-c52f5b96d0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69fb2e35-b76b-40f4-aaee-bf36dac74111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kodeBatang</value>
      <webElementGuid>42322ff0-5ba2-4d98-a699-dc1fe0b64dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>01234-5678</value>
      <webElementGuid>ba95397b-a733-470c-8208-7f033790ad20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full py-2 px-3 border-2 border-gray-400 rounded-lg focus:outline-none</value>
      <webElementGuid>d1d6e8d4-fc7c-4cc8-aa1f-ba0b97294608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-[#F2F2F2]&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;w-full ml-[255px]&quot;]/div[@class=&quot;px-6 w-full flex gap-6&quot;]/div[@class=&quot;w-3/5&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full p-6 bg-white rounded-lg mt-5&quot;]/div[@class=&quot;flex justify-between items-center gap-6 mb-4&quot;]/div[@class=&quot;w-full&quot;]/input[@class=&quot;w-full py-2 px-3 border-2 border-gray-400 rounded-lg focus:outline-none&quot;]</value>
      <webElementGuid>8ebc2b0a-8659-41ec-b2f4-9dd42660c154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kodeBatang']</value>
      <webElementGuid>21c6c4d5-5f45-43ee-8170-4023d2c0fba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>d7543bdb-5203-476d-81e3-4ba4473e67b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>4aa57be3-4654-4b6c-a68e-ae0cc71325f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'kodeBatang' and @placeholder = '01234-5678']</value>
      <webElementGuid>3da20024-6c30-4625-af44-376ccb808459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
